export const MODAL_OPEN = "MODAL_OPEN";

export const REDIRECT_SELECTED = "REDIRECT_SELECTED";

export const REDIRECT_FETCH_REQUESTED = "REDIRECT_FETCH_REQUESTED";
export const REDIRECT_FETCH_SUCCEEDED = "REDIRECT_FETCH_SUCCEEDED";
export const REDIRECT_FETCH_FAILED = "REDIRECT_FETCH_FAILED";

export const REDIRECT_ADD_REQUESTED = "REDIRECT_ADD_REQUESTED";
export const REDIRECT_ADD_SUCCEEDED = "REDIRECT_ADD_SUCCEEDED";
export const REDIRECT_ADD_FAILED = "REDIRECT_ADD_FAILED";

export const REDIRECT_UPDATE_REQUESTED = "REDIRECT_UPDATE_REQUESTED";
export const REDIRECT_UPDATE_SUCCEEDED = "REDIRECT_UPDATE_SUCCEEDED";
export const REDIRECT_UPDATE_FAILED = "REDIRECT_UPDATE_FAILED";

export const REDIRECT_DELETE_REQUESTED = "REDIRECT_DELETE_REQUESTED";
export const REDIRECT_DELETE_SUCCEEDED = "REDIRECT_DELETE_SUCCEEDED";
export const REDIRECT_DELETE_FAILED = "REDIRECT_DELETE_FAILED";
