name: CI

on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        mongodb-version: ["4.2", "4.4", "5.0"]
        redis-version: [4, 5, 6]
    env:
      AWS_COGNITO_USERNAME: ${{ secrets.AWS_COGNITO_USERNAME_CI }}
      AWS_COGNITO_PASSWORD: ${{ secrets.AWS_COGNITO_PASSWORD_CI }}
      AWS_COGNITO_USER_ID: ${{ secrets.AWS_COGNITO_USER_ID_CI }}
      MONGODB_URI: ${{ secrets.MONGODB_URI_CI }}
      REDIS_URL: ${{ secrets.REDIS_URL_CI }}
      SENTRY_DSN: ${{ secrets.SENTRY_DSN_CI }}
      NEXT_PUBLIC_ENVIRONMENT_ID: ${{ secrets.NEXT_PUBLIC_ENVIRONMENT_ID_CI }}
    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: ${{ matrix.mongodb-version }}

      - name: Start Redis
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: ${{ matrix.redis-version }}

      - run: yarn install

      - run: yarn run build

      - run: yarn run test:e2e
        env:
          CI: true
